version: "3.7"
services:
  node:
    build: .
    init: true
    restart: on-failure:3
    environment:
      - GC_URL=YOUR_URL_IS_HERE
      - DISCORD_TOKEN=YOUR_DISCORD_TOKEN_IS_HERE
      - DISCORD_GUILD_ID=YOUR_GUILD_ID_IS_HERE
      - DISCORD_BOT_ID=YOUR_BOT_ID_IS_HERE
    ports:
      - "127.0.0.1:3000:3000"